[package]
name = "olympus-analytics-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
oae-core = { path = "crates/oae-core" }
oae-data = { path = "crates/oae-data" }
oae-storage = { path = "crates/oae-storage" }
tempfile = "3.27"
fitparser = "0.11.0"

[workspace]
members = [
    "crates/oae-core",
    "crates/oae-analytics",
    "crates/oae-api",
    "crates/oae-storage", "crates/oae-data",
]

resolver = "3"
